import {
  mobile,
  backend,
  creator,
  web,
  css,
  git,
  html,
  mongodb,
  nextjs,
  express,
  javascript,
  nodejs,
  reactjs,
  redux,
  tailwind,
  typescript,
  threejs,
  henry,
  logo,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "FullStack Developer",
    icon: web,
  },
  {
    title: "Resourceful Problem Solver",
    icon: mobile,
  },
  {
    title: "Cat Lover",
    icon: backend,
  },
  {
    title: "Content Creator",
    icon: creator,
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "Express",
    icon: express,
  },
  {
    name: "TypeScript",
    icon: typescript,
  },
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "NextJS",
    icon: nextjs,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },
  {
    name: "MongoDB",
    icon: mongodb,
  },
  {
    name: "Three JS",
    icon: threejs,
  },
  {
    name: "git",
    icon: git,
  },
];

const experiences = [
  {
    title: "Fullstack Javascript Developer",
    company_name: "Bootcamp Soy Henry",
    icon: henry,
    iconBg: "#383E56",
    date: "March 2023 - July 2023",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including instructors, teaching assistants, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Fullstack Javascript Developer",
    company_name: "Freelancer",
    icon: logo,
    iconBg: "#E6DEDD",
    date: "Jan 2022 - Present",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams, clients, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Electrician",
    company_name: "Techint",
    icon: "https://www.liblogo.com/img-logo/te7978t06b-techint-logo-techint-grupo-doss-arq.png",
    iconBg: "#383E56",
    date: "Jan 2018 - March 2020",
    points: [
      "Coordinating the implementation of a robotic arm and surveying and connecting PLCs.",
      "Managing projects and ensuring their successful completion on time, within budget, and to the required specifications.",
      "Collaborating with team members to identify and resolve problems during the implementation phase.",
      "Assembling and connecting various projects related to PLCs and robotics for seamless pipes.",
      "Monitoring and controlling processes to ensure efficient and effective project execution.",
      "Developing plans to address potential issues and mitigate risks.",
      "Experience in managing projects, collaborating effectively with team members, and controlling processes is highly relevant to a career as a FullStack developer, where these skills are critical for designing, building, and maintaining complex web applications.",
    ],
  },
];

const testimonials = [
  {
    testimonial:
      "I'm a random user generated by Federico, so you can really trust me when I say that Federico really cares about the final product version that will reach the customer.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Cool Company",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I'm another random user, and I have to say that I've never met a web developer who cares as much about their users' success as Federico does.",
    name: "Chris Brown",
    designation: "COO",
    company: "Amazing Company",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "No, I am not another random user. I am the boss here. My human feeds me, and that's all that matters. Although I can attest to the fact that they spend their time studying and practicing to create websites that delight users. Anyway, hire him so he can buy me food!",
    name: "Vainilla",
    designation: "CTO",
    company: "House of Federico",
    image:
      "https://media.istockphoto.com/id/1393862021/photo/tricolor-cat-with-green-eyes.jpg?s=612x612&w=0&k=20&c=aF-wxBDRwgfoIN383qh9okzqC_9zm85njzlUvEhtCJU=",
  },
];

const projects = [
  {
    name: "GPT-3 Modern Landing",
    description:
      "Landing page that showcases the capabilities of GPT-3 and other modern web development tools. It has a modern and attractive design and offers an interactive demo of a chatbot powered by GPT-3. The page also includes user testimonials. Overall, the landing page demonstrates how GPT-3 and modern web development tools can be used to create interactive and efficient natural language processing applications and chatbots.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },

      {
        name: "tailwind",
        color: "pink-text-gradient",
      },
    ],
    image:
      "https://user-images.githubusercontent.com/63601533/238207413-cb45b8b5-21ac-4639-aae2-823d51b6b140.png",
    source_code_link: "https://github.com/FedeNicoletti/gpt3",
  },
  {
    name: "Modern Bank App",
    description:
      "Landing page that showcases an online banking application. The page has a modern and attractive design, and provides an overview of the banking services offered, such as current, savings, and investment accounts. It also describes the benefits of using the banking app, such as the ability to make online transfers and manage finances from anywhere.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },

      {
        name: "tailwind",
        color: "pink-text-gradient",
      },
    ],
    image:
      "https://user-images.githubusercontent.com/63601533/238207259-c6cbe422-719b-42ff-9115-a2c5848ce7aa.png",
    source_code_link: "https://github.com/FedeNicoletti/bank_app",
  },
  {
    name: "This Portfolio",
    description:
      "The page is a modern and minimalist developer's portfolio that presents a brief description of the developer and their skills, a section of projects with screenshots and links to repositories, and a contact form.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },

      {
        name: "tailwind",
        color: "pink-text-gradient",
      },
      {
        name: "Three JS",
        icon: threejs,
      },
    ],
    image:
      "https://user-images.githubusercontent.com/63601533/238207763-d71b37ec-4dc1-40c4-9644-f8ec051daecc.png",
    source_code_link: "https://github.com/FedeNicoletti/Portfolio",
  },
];

export { services, technologies, experiences, testimonials, projects };
